# provision_staging.yml
---
- name: Create ec2 instance
  hosts: all 
  #vars_files:
  #- vars.yml
  tasks:

  - name: Create instance 
    ec2:
      key_name: chouse
      instance_type: "{{ instance_type }}" 
      image: ami-048a01c78f7bae4aa
      wait: yes
      wait_timeout: 360
      group: ansible-container 
      instance_tags:
        awx-user: "{{ instance_tag }}"
        awx-dev: true
      count_tag:
        awx-user: "{{ instance_tag }}"
      exact_count: 1
      vpc_subnet_id: subnet-0321d3d8b84a2fa47
      assign_public_ip: yes  
      region: ap-southeast-1
      termination_protection: yes
    register: ec2
  
  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: awx_host
      ansible_user: ec2-user
    with_items: "{{ ec2.instances }}"
    when: ec2 is defined

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
    when: ec2 is defined

- name: Install Docker on the new EC2 instance
  hosts: awx_host
  become: yes
  roles:
  - role: docker
  tags: install_docker


